cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

services:
  - name: redis:latest
    alias: redis-ci

before_script:
  - npm install

.test_template: &unit_test
  script:
    - npm test

test:node_10:
  image: node:10
  <<: *unit_test

test:node_12:
  image: node:12
  <<: *unit_test

test:node_latest:
  image: node:latest
  <<: *unit_test